version: '3'

services:
  storefront:
    user: $UID:$GID
    build:
      context: .
    ports:
      - "9000:9000"
    volumes:
      - ./storefront:/storefront
    command: >
      sh -c "python manage.py runserver 0.0.0.0:9000"
    depends_on:
      - db
  
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ''
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
     - ./db:/var/lib/mysql
    restart: always

