# Generated by Django 3.2.16 on 2023-04-05 05:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c1e169f3-3a9a-40bd-b273-218e6a121490'), primary_key=True, serialize=False),
        ),
    ]
